drop 16.04 add 20.04
aeternity/machine-image pull request #28
Opened 2022-01-27 19:40 UTC by michalbagrowski

2022-02-01 11:21 UTC, venimus approved these changes

2022-02-22 10:34 UTC, dincho requested changes
We should add support (at least test pipeline) in the infrastructure repo first

2022-02-22 12:01 UTC, dincho commented
Could you please also update the admi-cleanup.py script

2022-05-25 10:22 UTC, dincho approved these changes

2022-05-25 10:23 UTC, merged